version: '3.8'
services:
    backend:
        env_file: '.env'
        build:
            context: .
            dockerfile: dockerfiles/django/Dockerfile
        ports:
            - 8000:8000
        volumes:
            - .:/app
        depends_on:
            - db
    db:
        env_file: '.env'
        restart: always
        image: postgres:alpine
        volumes:
            - .dbdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
