version: '3.8'
services:
    backend:
        env_file: '.env'
        build:
            context: .
            dockerfile: dockerfiles/django/Dockerfile
        ports:
            - 8000:8000
        volumes:
            - .:/app
